const listProductData = {
  listProduct: [
    {
      id: 1,
      name: "Glucosamine",
      quantity: 650,
      description:
        "Glucosamine And Chondroitin JpanWell hỗ trợ bổ sung chất nhờn dịch khớp, giúp khớp vận động linh hoạt, hỗ trợ giảm đau khớp, khô khớp do viêm khớp và thoái hóa khớp.",
      rootPrice: 100000,
      floorPrice: 750000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 120V",
      supply: "Gensei Nhật Bản",
      origin: "Gensei Nhật Bản",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/128x128/https://cms-prod.s3-sgn09.fptcloud.com/00032918_glucosamine_and_chondroitin_jpanwell_120v_9745_61a5_large_41ffa86dc1.JPG",
      codeProduct: "S0001",
      phoneNumber: "0987654321",
    },
    {
      id: 2,
      name: "Multivitamin",
      quantity: 500,
      description:
        "Multivitamin +Zn +D3 Royal Care hỗ trợ tăng cường sức khỏe, nâng cao sức đề kháng, giảm mệt mỏi",
      rootPrice: 100000,
      floorPrice: 175000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 60V",
      supply: "VESTA",
      origin: "VESTA VN",
      avatar:"https://cdn.nhathuoclongchau.com.vn/unsafe/636x0/filters:quality(90)/https://cms-prod.s3-sgn09.fptcloud.com/00500791_vien_uong_tang_de_khang_multivitamin_zn_d3_royal_care_60v_1169_62be_large_6f3a54bfa4.jpg",
      codeProduct: "S0002",
      phoneNumber: "0987654321",
    },
    {
      id: 3,
      name: "Léana Ocavill",
      quantity: 550,
      description:
        "Léana Ocavill hỗ trợ cân bằng nội tiết tố. Hỗ trợ cải thiện các triệu chứng thời kỳ tiền mãn kinh, mãn kinh do suy giảm nội tiết tố. Hỗ trợ hạn chế quá trình lão hóa, giúp đẹp da",
      rootPrice: 100000,
      floorPrice: 544000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 60V",
      supply: "Công ty Dược ",
      origin: "Hà Thành",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/00500122_vien_uong_ho_tro_can_bang_noi_tiet_to_leana_ocavill_60v_7335_628b_large_f28d3d0fc2.jpg",
      codeProduct: "S0007",
      phoneNumber: "0987654321",
    },
    {
      id: 4,
      name: "Ironmen Ocavill",
      quantity: 550,
      description:"Ironmen là thực phẩm bảo vệ sức khỏe giúp tăng cường sinh lý nam nhờ sự kết hợp giữa các thảo dược. Cung cấp năng lượng, bồi bổ sinh lực hiệu quả.",
      rootPrice: 100000,
      floorPrice: 680000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 60V",
      supply: "Bulgaria",
      origin: "Bulgaria",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/00501597_vien_uong_tang_cuong_sinh_ly_ironmen_ocavill_60v_5022_6302_large_3cb863cf94.jpg",
      codeProduct: "S0003",
      phoneNumber: "0987654321",
    },
    {
      id: 5,
      name: "Hoa Anh Thảo",
      quantity: 880,
      description:
        "Kenkan Seishun Primrose bổ sung dầu hoa anh thảo và isoflavone giúp hỗ trợ cải thiện các triệu chứng của phụ nữ tiền mãn kinh, mãn kinh như: Bốc hỏa, căng thẳng, lo âu.",
      rootPrice: 100000,
      floorPrice: 515000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 60V",
      supply: "Kenkan Seishun",
      origin: "Kenkan Seishun",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/00502210_vien_uong_bo_sung_dau_hoa_anh_thao_cho_phu_nu_tien_man_kinh_kenkan_seishun_primrose_60v_5885_6334_large_f92ec17740.jpg",
      codeProduct: "S0004",
      phoneNumber: "0987654321",
    },
    {
      id: 6,
      name: "SN Bổ Thận",
      quantity: 400,
      description:
        "Sâm Nhung Bổ Thận NV giúp bổ thận, tráng dương, mạnh gân cốt, ăn ngủ tốt, tăng cường sinh lực, giúp giảm tình trạng mãn dục nam, yếu sinh lý, đau lưng, mỏi gối.",
      rootPrice: 100000,
      floorPrice: 680000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 60V",
      supply: "Hải Linh",
      origin: "Hải Linh",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/IMG_3754_319065b5fe.jpg",
      codeProduct: "S0005",
      phoneNumber: "0987654321",
    },
    {
      id: 7,
      name: "NeoAqua Expert Cream",
      quantity: 400,
      description:"Kem dưỡng ẩm chuyên sâu NeoAqua Expert Cream với thành phần chuẩn Châu Âu (European Standard Ingredients) như: Aquaxyl, Tảo biển đỏ, Urea, Sodium Hyaluronate và Vitamin E,… sẽ đẩy nhanh quá trình cấp ẩm, tăng cường và củng cố hàng rào bảo vệ da khỏi tình trạng mất nước. Chất kem mỏng mịn thẩm thấu sâu vào lớp biểu bì da giúp mang lại nét đẹp tươi tắn và căng bóng ngay cả khi không trang điểm.",
      rootPrice: 100000,
      floorPrice: 516000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Hộp 50g",
      supply: "Lavita",
      origin: "Việt Nam",
      avatar:"https://cdn.nhathuoclongchau.com.vn/unsafe/373x0/filters:quality(90)/https://cms-prod.s3-sgn09.fptcloud.com/neoaqua_hop_lo_6c25dee43c.jpg",
      codeProduct: "S0006",
      phoneNumber: "0987654321",
    },
    {
      id: 8,
      name: "Dầu gội thảo dược",
      quantity: 400,
      description:"Dầu gội thảo dược La Beauty 300ml giúp làm sạch tóc, loại bỏ dầu nhờn trên da đầu, ngăn ngừa tình trạng nấm và gàu. Đồng thời, sản phẩm giúp củng cố chân tóc chắc khỏe, hỗ trợ giảm gãy rụng. Tăng cường các dưỡng chất tốt lành từ thiên nhiên để nuôi dưỡng da dầu và tóc phát triển khỏe mạnh, suôn mượt.",
      rootPrice: 100000,
      floorPrice: 115000,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Chai 300ml",
      supply: "Lavita",
      origin: "Lavita",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/DSC_00604_429bea69b5.jpg",
      codeProduct: "S0008",
      phoneNumber: "0987654321",
    },
    {
      id: 9,
      name: "Dầu xả hoa bưởi",
      quantity: 400,
      description:"Dầu xả Hoa Bưởi La Beauty 300ml làm sạch mềm tóc và ngăn ngừa gãy rụng. Đồng thời, tăng cường dưỡng chất cho mái tóc chắc khỏe.",
      rootPrice: 50000,
      floorPrice: 71200,
      expiry: "22/12/2023",
      updateAt: "",
      unit: "1 Chai 250ml",
      supply: "Lavita",
      origin: "Lavita",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/256x256/https://cms-prod.s3-sgn09.fptcloud.com/00030085_dau_xa_hoa_buoi_la_beauty_250ml_giam_gay_rung_kich_thich_moc_toc_6449_62ae_large_487f39d167.JPG",
      codeProduct: "S0009",
      phoneNumber: "0987654321",
    },
    {
      id: 10,
      name: "Pikolin Ocavill",
      quantity: 800,
      description:
        "Pikolin Ocavill hỗ trợ tăng tuần hoàn máu não. Hỗ trợ cải thiện các triệu chứng do thiểu năng tuần hoàn não. Hỗ trợ giảm nguy cơ hình thành cục máu đông và giảm di chứng sau tai biến mạch máu não do tắc mạch.",
      rootPrice: 100000,
      floorPrice: 490000,
      exprir: "22/12/2023",
      updateAt: "",
      unit: "1 Lọ 60V",
      supply: "PHYTOPHARMA LTD",
      origin: "PHYTOPHARMA LTD",
      avatar:
        "https://cdn.nhathuoclongchau.com.vn/unsafe/373x0/filters:quality(90)/https://cms-prod.s3-sgn09.fptcloud.com/00503017_vien_uong_tang_tuan_hoan_mau_nao_pikolin_ocavill_hop_30v_7705_63aa_large_900f06631e.jpg",
      codeProduct: "S0010",
      phoneNumber: "5432167890",
    },
  ],
  key: "list-product",
};

export {listProductData};
